### ISSUE TITLE
Include warnings for code blocks with long runtimes

### ISSUE THREAD

**Issue by jnuesca** [andrawis97/Hacking-Food---Team-Harvey-Willey#11]
Multiple code blocks are taking forever to run. Would recommend a warning for users (comment or documentation) running through your code stating the estimated run time for some of these blocks. You could also break up some of what you are trying to do into multiple code blocks (for example demand curves for several goods).

I am having issues running:

- Demand curves

- Engel curve for different nutritions

**Comment by andrawis97** [comment]
[link](https://github.com/andrawis97/Hacking-Food---Team-Harvey-Willey/issues/8)  raised a similar topic.

I like the warning message for run-time and will implement that.  The reason our data is taking so long is because when we ran it we were concerned with the output and the runtime was a reasnoble tradeoff for us. Will take note of run time in the future.
