### ISSUE TITLE
Explain budget constraint

### ISSUE THREAD

**Issue by jnuesca** [andrawis97/Hacking-Food---Team-Harvey-Willey#5]
How did you get this budget constraint of 10,690 TZS in 2008? Would like more clarification of where this number came from or if it's arbitrary.

**Comment by clairevparkinson** [comment]
We got this number from Numbeo as the "Daily recommended minimum amount of money for food per person" in Tanzania. Note that the number has slightly changed on the website since we retrieved it by about 40 shillings (about $0.01 USD).

Link here: https://www.numbeo.com/food-prices/country_result.jsp?country=Tanzania&fbclid=IwAR01xSG24wjkqDEg3hAK3QIHOgAj-tePe5K7UFzoYmxEoKHMjgFio8YQ4Uk

**Comment by clairevparkinson** [comment]
We have also updated the notebook to explain where this number came from and link to the source. Will be committed soon.
